version: '3.8'

services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.24.2
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    networks:
      sparrow-network:
        ipv4_address: 192.168.1.100

  sparrow:
    build:
      context: .
    environment:
      - PORT=8000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    runtime: nvidia
    command: bash -c "source ~/.bashrc && python3.10 api.py --port 8000"
    networks:
      sparrow-network:
        ipv4_address: 192.168.1.101

volumes:
  weaviate_data:

networks:
  sparrow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24